### ISSUE TITLE
Only hum

### ISSUE THREAD

**Issue by zweann** [rkinnett/ESP32-2-Way-Audio-Relay#3] opened 2022-06-22 11:18 UTC
Hello!
Thank you for this nice project. This is exactly what I was looking for!

I tried to stream analog audio from a headphone source via my ESP32 to the Banana VBAN software, but the only thing I could here was hum. I used ADC GPIO 33 as shown in the schematic.

Do you have any hints?

**Comment by rkinnett** [comment] 2022-06-24 16:37
There are hundreds of things that could be going wrong, and just as many troubleshooting steps you could take to isolate the problem.  To outline a few:
- double check audio source volume
- double check VBAN configuration (it's touchy)
- With an oscilloscope or digital multimeter, measure the signal into the ADC to make sure you have usable signal (in the 0-3V range with ~1.63V bias).
- Add lines to the arduino code to print to serial min and max values to confirm it's digitizing in the expected range.
- View the ADC measurements using this:   https://github.com/rkinnett/ESP32-ADC-Plotter-Demo
- Write an arduino program to generate a constant tone and transmit over UDP to VBAN.

I'll close this issue since it's not clear that the problem is with this code, but we can continue to talk in this ticket, and I can reopen it if we do identify a problem with the code.

**Closed as completed by rkinnett** 2022-06-24 16:37 UTC

**Comment by zweann** [comment] 2022-06-28 12:44
Thank you very much for your answer and your patience!
The bias in my setup was completely wrong, sorry for that! Now it's working very well!

The only thing I can't get working, is to send audio from my PC to the ESP. The ESP never switches into the transmit mode. I tried this with the banana software and the VBAN Talkie software with different sample rates and used the ESP console to get the current state. But it stays in the receive mode.

**Comment by rkinnett** [comment] 2022-06-28 16:45
I’m glad to hear the esp32->pc side of the link is working :)

For the outgoing link (pc->esp32), monitor usb serial from the esp32 to confirm udp connection status messages make sense.  Make sure vban banana is setup to send data in 16 bits and make sure you’re sourcing some sound from your pc - online tone generator, music file, etc.  Uncomment line 612 in order to confirm that the esp32 receives packets from vban.  If that doesn’t show any packets coming in then you may need to look more at the vban banana configuration and maybe even network/firewall/router settings to make sure the pc is sending packets and they’re not getting blocked somewhere.  If you have access to another pc you could setup vban babana there and try to make a pc-pc link.  Also wireshark could be useful to confirm packets are going out.

**Comment by zweann** [comment] 2022-09-13 16:14
Hi @rkinnett 

I tried again a little bit with VBAN. In my network I am able to stream VBAN from any pc to any other pc on any port, so network should be fine.
I again tried to stream audio to the ESP32, without success. Is it important to use a specific stream name? To send audio from ESP32 to PC I use the predefined name "ESP32_AUDIO_STRM" which is working fine.

**Comment by zweann** [comment] 2022-09-13 16:37
> Hi @rkinnett
> 
> I tried again a little bit with VBAN. In my network I am able to stream VBAN from any pc to any other pc on any port, so network should be fine. I again tried to stream audio to the ESP32, without success. Is it important to use a specific stream name? To send audio from ESP32 to PC I use the predefined name "ESP32_AUDIO_STRM" which is working fine.

OK, I got it!
When I use the ESP in my home network without its own access point, the ESP is just sending data, not receiving. Is this meant to be?
